# Generated by Django 4.2.4 on 2023-08-11 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
    ]
